# -*- coding: utf-8 -*-
"""entrega.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLmaZj5T48Pa-dgttLexsDKytkZOzql4
"""

from geopy.geocoders import Nominatim
import folium
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns

tur = pd.read_excel("turismo-Can-Tnf-Lzn.xlsx")
ben = pd.read_excel("beneficioTurismo.xlsx")

# Contraste entre canarias, tenerife, lanzarote en numeros de turista mensuales

tur.plot(kind="line", x='Mes', y=['Lanzarote', 'Tenerife'])
plt.title("Contraste entre tenerife ylanzarote en numeros de turista mensuales")
plt.xlabel("Mes")
plt.ylabel("Numero de turistas")
plt.show()

# Contraste entre canarias, tenerife, lanzarote en beneficios hosteleros mensuales

ben.plot(kind="line", x='Mes', y=['Lanzarote', 'Tenerife'])
plt.title("Contraste entre tenerife y lanzarote en beneficios hosteleros mensuales")
plt.xlabel("Mes")
plt.ylabel("Beneficios")
plt.show()

# Correlacion entre numero de turistas y beneficio hostelero
ben = ben.rename(columns={'Mes': 'bMes'})
turben = pd.merge(tur, ben, left_on='Mes', right_on='bMes', how='left').drop('bMes', axis=1)
turben
# Correccion de medidas para visualizacion
turben['Lanzarote_x'] = turben['Lanzarote_x'].apply(lambda x: x * 100000)
turben['Tenerife_x'] = turben['Tenerife_x'].apply(lambda x: x * 100000)
turben = turben.rename(columns={'Lanzarote_x': 'num_turistas_Lanzarote', 'Lanzarote_y': 'beneficio_Lanzarote', 'Tenerife_x': 'num_turistas_Tenerife', 'Tenerife_y': 'beneficio_Tenerife'})
turben.plot(kind="line", x = 'Mes', y = ['num_turistas_Lanzarote', 'beneficio_Lanzarote', 'num_turistas_Tenerife', 'beneficio_Tenerife'])
plt.title("Contraste entre tenerife y lanzarote en beneficios hosteleros mensuales")
plt.xlabel("Mes")
plt.ylabel("Beneficios en cientos de miles")
plt.show()